org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft Version
minecraft_version=26.3
# Architectury Loom Version
loom_version=1.17-SNAPSHOT
# Fabric Loader Version
loader_version=0.19.5

# Mod Properties
mod_version=1.7.0
maven_group=com.glow.hidearmor
archives_base_name=hidearmor
mod_id=hidearmor

# Dependencies
fabric_api_version=0.161.0+26.3
architectury_api_version=22.0.2
neoforge_version=26.3.0.10-beta
